// packages/@uppy/svelte/src/lib/components/Dashboard.svelte
<script
  lang="ts"
  generics="M extends import('@uppy/utils').Meta, B extends import('@uppy/utils').Body"
>
import type { Uppy } from "@uppy/core";
import DashboardPlugin from "@uppy/dashboard";
import { onDestroy, onMount } from "svelte";

let container: HTMLElement;
let plugin: DashboardPlugin<M, B>;

export let uppy: Uppy<M, B>;
export const props: Object | undefined = {};
export const plugins: string[] = [];

const installPlugin = () => {
	const options = {
		id: "svelte:Dashboard",
		inline: true,
		plugins,
		...props,
		target: container,
	};

	uppy.use(DashboardPlugin, options);
	plugin = uppy.getPlugin(options.id) as DashboardPlugin<M, B>;
};
const uninstallPlugin = (uppyInstance: Uppy<M, B> = uppy) => {
	if (plugin != null) uppyInstance.removePlugin(plugin);
};

onMount(() => installPlugin());

onDestroy(() => uninstallPlugin());
$: {
	const options = {
		id: "svelte:Dashboard",
		inline: true,
		plugins,
		...props,
		target: container,
	};
	uppy.setOptions(options);
}
</script>

<div class="uppy-Container" bind:this={container}></div>

// packages/@uppy/vue/src/Dashboard.vue
<template>
  <div ref="container" />
</template>
<script>
import DashboardPlugin from '@uppy/dashboard'

export default {
  data () {
    return {
      plugin: null
    }
  },
  props: {
    uppy: {
      required: true
    },
    props: {
      type: Object
    },
    plugins: {
      type: Array
    }
  },
  mounted () {
    this.installPlugin()
  },
  methods: {
    installPlugin () {
      const uppy = this.uppy
      const options = {
        id: 'vue:Dashboard',
        inline: true,
        plugins: this.plugins,
        ...this.props,
        target: this.$refs.container
      }
      uppy.use(DashboardPlugin, options)
      this.plugin = uppy.getPlugin(options.id)
    },
    uninstallPlugin (uppy = this.uppy) {
      uppy.removePlugin(this.plugin)
    }
  },
  beforeDestroy () {
    this.uninstallPlugin()
  },
  watch: {
    uppy (current, old) {
      if (old !== current) {
        this.uninstallPlugin(old)
        this.installPlugin()
      }
    },
    props (current, old) {
      if (JSON.stringify(old) !== JSON.stringify(current)) {
        this.plugin.setOptions(current)
      }
    }
  }
}
</script>
