// packages/@uppy/svelte/src/components/StatusBar.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { Uppy } from '@uppy/core';
  import StatusBarPlugin from '@uppy/status-bar'

  let container: HTMLElement;
  let plugin: StatusBarPlugin; 

  export let uppy: Uppy;
  export let props: Object | undefined = {};

  const installPlugin = () => {
    const options = {
      id: 'svelte:StatusBar',
      inline: true,
      ...props,
      target: container
    }

    uppy.use(StatusBarPlugin, options);
    plugin = uppy.getPlugin(options.id) as StatusBarPlugin;
  }
  const uninstallPlugin = (uppyInstance: Uppy = uppy) => {
    uppyInstance.removePlugin(plugin);
  }

  onMount(() => installPlugin())

  onDestroy(() => uninstallPlugin())
  $: {
    const options = {
      id: 'svelte:StatusBar',
      ...props,
      target: container
    }
    uppy.setOptions(options)
  }
</script>
<div bind:this={container} />

// packages/@uppy/vue/src/StatusBar.vue
<template>
  <div ref="container" />
</template>
<script>
import StatusBarPlugin from '@uppy/status-bar'

export default {
  data () {
    return {
      plugin: null
    }
  },
  props: {
    uppy: {
      required: true
    },
    props: {
      type: Object
    }
  },
  mounted () {
    this.installPlugin()
  },
  methods: {
    installPlugin () {
      const uppy = this.uppy
      const options = {
        id: 'vue:StatusBar',
        ...this.props,
        target: this.$refs.container
      }
      uppy.use(StatusBarPlugin, options)
      this.plugin = uppy.getPlugin(options.id)
    },
    uninstallPlugin (uppy = this.uppy) {
      uppy.removePlugin(this.plugin)
    }
  },
  beforeDestroy () {
    this.uninstallPlugin()
  },
  watch: {
    uppy (current, old) {
      if (old !== current) {
        this.uninstallPlugin(old)
        this.installPlugin()
      }
    },
    props (current, old) {
      if (JSON.stringify(old) !== JSON.stringify(current)) {
        this.uninstallPlugin()
        this.installPlugin()
      }
    }
  }
}
</script>
