// packages/@uppy/react/src/ProgressBar.ts
import { createElement as h, Component } from 'react'
import type { UnknownPlugin, Uppy } from '@uppy/core'
import ProgressBarPlugin, { type ProgressBarOptions } from '@uppy/progress-bar'
import type { Body, Meta } from '@uppy/utils/lib/UppyFile'
import getHTMLProps from './getHTMLProps.js'
import nonHtmlPropsHaveChanged from './nonHtmlPropsHaveChanged.js'

interface ProgressBarProps<M extends Meta, B extends Body>
  extends ProgressBarOptions {
  uppy: Uppy<M, B>
}

/**
 * React component that renders a progress bar at the top of the page.
 */

class ProgressBar<M extends Meta, B extends Body> extends Component<
  ProgressBarProps<M, B>
> {
  private container!: HTMLElement

  private plugin!: UnknownPlugin<M, B>

  componentDidMount(): void {
    this.installPlugin()
  }

  componentDidUpdate(prevProps: ProgressBar<M, B>['props']): void {
    // eslint-disable-next-line react/destructuring-assignment
    if (prevProps.uppy !== this.props.uppy) {
      this.uninstallPlugin(prevProps)
      this.installPlugin()
    } else if (nonHtmlPropsHaveChanged(this.props, prevProps)) {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { uppy, ...options } = { ...this.props, target: this.container }
      this.plugin.setOptions(options)
    }
  }

  componentWillUnmount(): void {
    this.uninstallPlugin()
  }

  installPlugin(): void {
    const { uppy, fixed, hideAfterFinish, id } = this.props
    const options = {
      id: id || 'ProgressBar',
      fixed,
      hideAfterFinish,
      target: this.container,
    }

    uppy.use(ProgressBarPlugin, options)

    this.plugin = uppy.getPlugin(options.id)!
  }

  uninstallPlugin(props = this.props): void {
    const { uppy } = props

    uppy.removePlugin(this.plugin)
  }

  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  render() {
    return h('div', {
      className: 'uppy-Container',
      ref: (container: HTMLElement) => {
        this.container = container
      },
      ...getHTMLProps(this.props),
    })
  }
}

export default ProgressBar

// packages/@uppy/svelte/src/lib/components/ProgressBar.svelte
<script
  lang="ts"
  generics="M extends import('@uppy/utils/lib/UppyFile').Meta, B extends import('@uppy/utils/lib/UppyFile').Body"
>
import type { Uppy } from "@uppy/core";
import ProgressBarPlugin, { type ProgressBarOptions } from "@uppy/progress-bar";
import { onDestroy, onMount } from "svelte";

let container: HTMLElement;
let plugin: ProgressBarPlugin<M, B>;

export let uppy: Uppy<M, B>;
export let props: ProgressBarOptions | undefined = {};

const installPlugin = () => {
	const options = {
		id: "svelte:ProgressBar",
		...props,
		target: container,
	} satisfies ProgressBarOptions;

	uppy.use(ProgressBarPlugin<M, B>, options);
	plugin = uppy.getPlugin(options.id) as ProgressBarPlugin<M, B>;
};
const uninstallPlugin = (uppyInstance: Uppy<M, B> = uppy) => {
	if (plugin != null) uppyInstance.removePlugin(plugin);
};

onMount(() => installPlugin());

onDestroy(() => uninstallPlugin());
$: {
	const options = {
		id: "svelte:ProgressBar",
		...props,
		target: container,
	} satisfies ProgressBarOptions;
	uppy.setOptions(options);
}
</script>

<div class="uppy-Container" bind:this={container}></div>
