// packages/@uppy/vue/src/StatusBar.vue
<template>
  <div ref="container" />
</template>
<script lang="ts">
import Vue, { PropType } from 'vue'
import type { Uppy, Plugin } from '@uppy/core'
import StatusBarPlugin from '@uppy/status-bar'
import { shallowEqualObjects } from 'shallow-equal'

interface Data {
  plugin: Plugin
}
interface Props {
  uppy: Uppy,
  props: Object,
}
interface Methods {
  installPlugin(): void,
  uninstallPlugin(uppy: Uppy): void,
}

export default Vue.extend<Data, Methods, unknown, Props>({
  data () {
    return {
      plugin: {} as Plugin
    }
  },
  props: {
    uppy: {
      required: true
    },
    props: {
      type: Object
    }
  },
  mounted () {
    this.installPlugin()
  },
  methods: {
    installPlugin () {
      const uppy = this.uppy
      const options = {
        id: 'vue:StatusBar',
        ...this.props,
        target: this.$refs.container
      }
      uppy.use(StatusBarPlugin, options)
      this.plugin = uppy.getPlugin(options.id)
    },
    uninstallPlugin (uppy: Uppy) {
      uppy.removePlugin(this.plugin)
    }
  },
  beforeDestroy () {
    this.uninstallPlugin(this.uppy)
  },
  watch: {
    uppy (current, old) {
      if (old !== current) {
        this.uninstallPlugin(old)
        this.installPlugin()
      }
    },
    props (current, old) {
      if (!shallowEqualObjects(current, old)) {
        this.plugin.setOptions(current)
      }
    }
  }
})
</script>

// packages/@uppy/svelte/src/lib/components/StatusBar.svelte
<script
  lang="ts"
  generics="M extends import('@uppy/utils/lib/UppyFile').Meta, B extends import('@uppy/utils/lib/UppyFile').Body"
>
import type { Uppy } from "@uppy/core";
import StatusBarPlugin from "@uppy/status-bar";
import { onDestroy, onMount } from "svelte";

let container: HTMLElement;
let plugin: StatusBarPlugin<M, B>;

export let uppy: Uppy<M, B>;
export const props: Object | undefined = {};

const installPlugin = () => {
	const options = {
		id: "svelte:StatusBar",
		inline: true,
		...props,
		target: container,
	};

	uppy.use(StatusBarPlugin, options);
	plugin = uppy.getPlugin(options.id) as StatusBarPlugin<M, B>;
};
const uninstallPlugin = (uppyInstance: Uppy<M, B> = uppy) => {
	if (plugin != null) uppyInstance.removePlugin(plugin);
};

onMount(() => installPlugin());

onDestroy(() => uninstallPlugin());
$: {
	const options = {
		id: "svelte:StatusBar",
		...props,
		target: container,
	};
	uppy.setOptions(options);
}
</script>

<div class="uppy-Container" bind:this={container}></div>
