// examples/angular/src/app/app.component.ts
import { CommonModule } from '@angular/common'
import { Component, type OnInit } from '@angular/core'
import {
  DashboardComponent,
  DashboardModalComponent,
  DragDropComponent,
  ProgressBarComponent,
} from '@uppy/angular'
import { Uppy } from '@uppy/core'
import GoogleDrive from '@uppy/google-drive'
import Tus from '@uppy/tus'
import Webcam from '@uppy/webcam'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  standalone: true,
  imports: [
    CommonModule,
    DashboardComponent,
    DashboardModalComponent,
    DragDropComponent,
    ProgressBarComponent,
  ],
})
export class AppComponent implements OnInit {
  title = 'angular-example'

  showInline = false

  showModal = false

  dashboardProps = {
    plugins: ['Webcam'],
  }

  dashboardModalProps = {
    target: document.body,
    onRequestCloseModal: (): void => {
      this.showModal = false
    },
  }

  uppy = new Uppy({ debug: true, autoProceed: true })

  ngOnInit(): void {
    this.uppy
      .use(Webcam)
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })
      .use(GoogleDrive, { companionUrl: 'https://companion.uppy.io' })
  }
}

<h1>Uppy Angular Example!</h1>
<h2>Inline dashboard</h2>
<label>
  <input
    type="checkbox"
    (change)="showInline = $any($event.target)?.checked"
    [checked]="showInline"
  />
  Show Dashboard
</label>

<uppy-dashboard
  [uppy]="uppy"
  [props]="dashboardProps"
  *ngIf="showInline"
></uppy-dashboard>

<h2>Modal Dashboard</h2>
<div>
  <uppy-dashboard-modal
    [uppy]="uppy"
    [open]="showModal"
    [props]="dashboardModalProps"
  ></uppy-dashboard-modal>
  <button (click)="showModal = !showModal">
    {{ showModal ? 'Close dashboard' : 'Open dashboard' }}
  </button>
</div>

<h2>Drag Drop Area</h2>
<uppy-drag-drop [uppy]="uppy" [props]="{}"></uppy-drag-drop>

<h2>Progress Bar</h2>
<uppy-progress-bar
  [uppy]="uppy"
  [props]="{ hideAfterFinish: false }"
></uppy-progress-bar>

// examples/react-example/App.jsx
/* eslint-disable */
import React from'react'
import Uppy from'@uppy/core'
import Tus from'@uppy/tus'
import GoogleDrive from'@uppy/google-drive'
import { Dashboard, DashboardModal, DragDrop, ProgressBar, FileInput } from'@uppy/react'

import '@uppy/core/dist/style.css'
import '@uppy/dashboard/dist/style.css'
import '@uppy/drag-drop/dist/style.css'
import '@uppy/file-input/dist/style.css'
import '@uppy/progress-bar/dist/style.css'

export default class App extends React.Component {
  constructor (props) {
    super(props)

    this.state = {
      showInlineDashboard: false,
      open: false
    }

    this.uppy = new Uppy({ id: 'uppy1', autoProceed: true, debug: true })
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })
      .use(GoogleDrive, { companionUrl: 'https://companion.uppy.io' })

    this.uppy2 = new Uppy({ id: 'uppy2', autoProceed: false, debug: true })
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })

    this.handleModalClick = this.handleModalClick.bind(this)
  }

  componentWillUnmount () {
    this.uppy.close({ reason: 'unmount' })
    this.uppy2.close({ reason: 'unmount' })
  }

  handleModalClick () {
    this.setState({
      open: !this.state.open
    })
  }

  render () {
    const { showInlineDashboard } = this.state
    return (
      <div>
        <h1>React Examples</h1>

        <h2>Inline Dashboard</h2>
        <label>
          <input
            type="checkbox"
            checked={showInlineDashboard}
            onChange={(event) => {
              this.setState({
                showInlineDashboard: event.target.checked
              })
            }}
          />
          Show Dashboard
        </label>
        {showInlineDashboard && (
          <Dashboard
            uppy={this.uppy}
            plugins={['GoogleDrive']}
            metaFields={[
              { id: 'name', name: 'Name', placeholder: 'File name' }
            ]}
          />
        )}

        <h2>Modal Dashboard</h2>
        <div>
          <button onClick={this.handleModalClick}>
            {this.state.open ? 'Close dashboard' : 'Open dashboard'}
          </button>
          <DashboardModal
            uppy={this.uppy2}
            open={this.state.open}
            target={document.body}
            onRequestClose={() => this.setState({ open: false })}
          />
        </div>

        <h2>Drag Drop Area</h2>
        <DragDrop
          uppy={this.uppy}
          locale={{
            strings: {
              chooseFile: 'Boop a file',
              orDragDrop: 'or yoink it here'
            }
          }}
        />

        <h2>Progress Bar</h2>
        <ProgressBar
          uppy={this.uppy}
          hideAfterFinish={false}
        />

        <h2>File Input</h2>
        <FileInput
          uppy={this.uppy}
        />
      </div>
    )
  }
}
