// packages/@uppy/react/src/FilesList.tsx
import { useEffect, useRef, createElement as h, useContext } from 'react'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import {
  FilesList as PreactFilesList,
  type FilesListProps,
} from '@uppy/components'
import { UppyContext } from './UppyContextProvider.js'
import useReactRender from './useReactRender.js'

export default function FilesList({
  editFile,
  item,
}: Omit<FilesListProps, 'ctx' | 'render'>) {
  const ref = useRef(null)
  const ctx = useContext(UppyContext)
  const reactRender = useReactRender()

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactFilesList, {
          editFile,
          ctx,
          item,
          render: reactRender,
        } satisfies FilesListProps),
        ref.current,
      )
    }
  }, [ctx, editFile, item, reactRender])

  return <div ref={ref} />
}

// packages/@uppy/svelte/src/lib/components/headless/FilesList.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    FilesList as PreactFilesList,
    type FilesListProps,
    type UppyContext,
  } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: Omit<FilesListProps, 'ctx'> = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactFilesList, {
          ...props,
          ctx,
        } satisfies FilesListProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>
