// packages/@uppy/react/src/GoogleDrivePicker.tsx
import { useEffect, useRef, useContext, createElement as h } from 'react'
import {
  GoogleDrivePicker as PreactGoogleDrivePicker,
  type GoogleDrivePickerProps,
} from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import { UppyContext } from './UppyContextProvider.js'

export default function GoogleDrivePicker(
  props: Omit<GoogleDrivePickerProps, 'render' | 'ctx'>,
) {
  const ref = useRef(null)
  const ctx = useContext(UppyContext)

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactGoogleDrivePicker, {
          ...props,
          ctx,
        } satisfies GoogleDrivePickerProps),
        ref.current,
      )
    }
  }, [ctx, props])

  return h('div', { ref })
}

// packages/@uppy/svelte/src/lib/components/headless/GoogleDrivePicker.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    GoogleDrivePicker as PreactGoogleDrivePicker,
    type GoogleDrivePickerProps,
    type UppyContext,
  } from '@uppy/components'
  import { h as preactH } from 'preact'
  import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: Omit<GoogleDrivePickerProps, 'ctx' | 'render'> = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactGoogleDrivePicker, {
          ...props,
          ctx,
          render: (el, node) => {
            if (el) {
              mount(node, { target: el })
            }
          },
        } satisfies GoogleDrivePickerProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>
