// packages/@uppy/react/src/NewFileInput.tsx
import { useEffect, useRef, useContext, createElement as h } from 'react'
import {
  FileInput as PreactFileInput,
  type FileInputProps,
} from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import { UppyContext } from './UppyContextProvider.js'
import useReactRender from './useReactRender.js'

export default function FileInput({
  multiple,
  accept,
  child,
  className,
}: Omit<FileInputProps, 'render' | 'ctx'>) {
  const ref = useRef(null)
  const ctx = useContext(UppyContext)
  const reactRender = useReactRender()

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactFileInput, {
          multiple,
          accept,
          child,
          className,
          ctx,
          render: reactRender,
        } satisfies FileInputProps),
        ref.current,
      )
    }
  }, [ctx, multiple, accept, child, className, reactRender])

  return h('div', { ref })
}

// packages/@uppy/svelte/src/lib/components/headless/NewFileInput.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    NewFileInput as PreactNewFileInput,
    type NewFileInputProps,
    type UppyContext,
  } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: Omit<NewFileInputProps, 'ctx'> = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactNewFileInput, {
          ...props,
          ctx,
        } satisfies NewFileInputProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>
