// packages/@uppy/react/src/Thumbnail.tsx
import { useEffect, useRef, createElement as h } from 'react'
import {
  Thumbnail as PreactThumbnail,
  type ThumbnailProps,
} from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import useReactRender from './useReactRender.js'

export default function Thumbnail(props: ThumbnailProps) {
  const ref = useRef(null)
  const reactRender = useReactRender()

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactThumbnail, {
          ...props,
          render: reactRender,
        } as ThumbnailProps),
        ref.current,
      )
    }
  }, [props, reactRender])

  return <div ref={ref} />
}

// packages/@uppy/svelte/src/lib/components/headless/Thumbnail.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    Thumbnail as PreactThumbnail,
    type ThumbnailProps,
    type UppyContext,
  } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: ThumbnailProps = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactThumbnail, {
          ...props,
          ctx,
        } satisfies ThumbnailProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>
