// packages/@uppy/react/src/headless/UploadButton.tsx
import { useEffect, useRef, useContext, createElement as h } from 'react'
import {
  UploadButton as PreactUploadButton,
  type UploadButtonProps,
} from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import { UppyContext } from './UppyContextProvider.js'

export default function UploadButton(props: Omit<UploadButtonProps, 'ctx'>) {
  const ref = useRef(null)
  const ctx = useContext(UppyContext)

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactUploadButton, {
          ...props,
          ctx,
        } satisfies UploadButtonProps),
        ref.current,
      )
    }
  }, [ctx, props])

  return <div ref={ref} />
}

// packages/@uppy/svelte/src/lib/components/headless/UploadButton.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    UploadButton as PreactUploadButton,
    type UploadButtonProps,
    type UppyContext,
  } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: Omit<UploadButtonProps, 'ctx'> = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactUploadButton, {
          ...props,
          ctx,
        } satisfies UploadButtonProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>
