// packages/@uppy/react/src/UploadButton.tsx
import { useEffect, useRef, createElement as h, useContext } from 'react'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import { UploadButton as PreactUploadButton } from '@uppy/components'
import { UppyContext } from './UppyContextProvider.js'

export default function UploadButton() {
  const ref = useRef(null)
  const ctx = useContext(UppyContext)

  useEffect(() => {
    if (ref.current) {
      preactRender(preactH(PreactUploadButton, { ctx }), ref.current)
    }
  }, [ctx])

  return <div ref={ref} />
}

// packages/@uppy/svelte/src/lib/components/headless/UploadButton.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    UploadButton as PreactUploadButton,
    type UploadButtonProps,
    type UppyContext,
  } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: UploadButtonProps = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactUploadButton, {
          ...props,
          ctx,
        } satisfies UploadButtonProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>
