// packages/@uppy/react/src/headless/UppyContextProvider.tsx
import React, {
  createContext,
  useState,
  useEffect,
  createElement as h,
} from 'react'
import type Uppy from '@uppy/core'
import { createUppyEventAdapter, type UploadStatus } from '@uppy/components'

interface UppyContextValue {
  uppy: Uppy | undefined
  status: UploadStatus
  progress: number
}

export const UppyContext = createContext<UppyContextValue>({
  uppy: undefined,
  status: 'init',
  progress: 0,
})

interface Props {
  uppy: Uppy
  children: React.ReactNode
}

export function UppyContextProvider({ uppy, children }: Props) {
  const [status, setStatus] = useState<UploadStatus>('init')
  const [progress, setProgress] = useState(0)

  useEffect(() => {
    if (!uppy) {
      throw new Error(
        'UppyContextProvider: passing `uppy` as a prop is required',
      )
    }

    const uppyEventAdapter = createUppyEventAdapter({
      uppy,
      onStatusChange: (newStatus: UploadStatus) => {
        setStatus(newStatus)
      },
      onProgressChange: (newProgress: number) => {
        setProgress(newProgress)
      },
    })

    return () => uppyEventAdapter.cleanup()
  }, [uppy])

  return (
    <UppyContext.Provider
      value={{
        uppy,
        status,
        progress,
      }}
    >
      {children}
    </UppyContext.Provider>
  )
}

export default UppyContextProvider

// packages/@uppy/svelte/src/lib/components/headless/UppyContextProvider.svelte
<script context="module" lang="ts">
  import type Uppy from '@uppy/core';
  import { createUppyEventAdapter, type UploadStatus } from '@uppy/components'

  export const UppyContextKey = 'uppy-context';
  export type { UppyContext } from '@uppy/components';
</script>

<script lang="ts">
  import { setContext, onMount } from 'svelte';

  export let uppy: Uppy;

  let status: UploadStatus = 'init';
  let progress = 0;

  onMount(() => {
    if (!uppy) {
      throw new Error(
        'ContextProvider: passing `uppy` as a prop is required',
      );
    }

    const uppyEventAdapter = createUppyEventAdapter({
      uppy,
      onStatusChange: (newStatus: UploadStatus) => {
        status = newStatus
      },
      onProgressChange: (newProgress: number) => {
        progress = newProgress
      },
    })

    return () => uppyEventAdapter.cleanup()
  });

  // Create a reactive store from our context values
  $: contextValue = {
    uppy,
    status,
    progress,
  };

  // Set the context for child components to use
  $: setContext(UppyContextKey, contextValue);
</script>

<slot />
