// examples/vue3/src/App.vue
<template>
  <UppyContextProvider :uppy="uppy">
    <main class="p-5 max-w-xl mx-auto">
      <h1 class="text-4xl font-bold">Welcome to Vue.</h1>

      <CustomDropzone />

      <article>
        <h2 class="text-2xl my-4">With list</h2>
        <Dropzone />
        <FilesList />
        <UploadButton />
      </article>

      <article>
        <h2 class="text-2xl my-4">With grid</h2>
        <Dropzone />
        <FilesGrid :columns="2" />
        <UploadButton />
      </article>
    </main>
  </UppyContextProvider>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import Uppy from '@uppy/core'
import Tus from '@uppy/tus'
import {
  UppyContextProvider,
  Dropzone,
  FilesList,
  FilesGrid,
  UploadButton,
} from '@uppy/vue'
import CustomDropzone from './Dropzone.vue'

const uppy = computed(() =>
  new Uppy().use(Tus, {
    endpoint: 'https://tusd.tusdemo.net/files/',
  }),
)
</script>

<style src="@uppy/vue/dist/styles.css"></style>

// examples/react/src/App.tsx
/* eslint-disable react/react-in-jsx-scope */
import { useState } from 'react'
import {
  Dropzone,
  FilesGrid,
  FilesList,
  UploadButton,
  UppyContextProvider,
} from '@uppy/react'
import Uppy from '@uppy/core'
import Tus from '@uppy/tus'

import './app.css'
import '@uppy/react/dist/styles.css'

function App() {
  const [uppy] = useState(() =>
    new Uppy().use(Tus, {
      endpoint: 'https://tusd.tusdemo.net/files/',
    }),
  )

  return (
    <UppyContextProvider uppy={uppy}>
      <main className="p-5 max-w-xl mx-auto">
        <h1 className="text-4xl font-bold">Welcome to React.</h1>

        <article>
          <h2 className="text-2xl my-4">With list</h2>
          <Dropzone />

          <FilesList />
          <UploadButton />
        </article>

        <article>
          <h2 className="text-2xl my-4">With grid</h2>
          <Dropzone />
          <FilesGrid columns={2} />
          <UploadButton />
        </article>
      </main>
    </UppyContextProvider>
  )
}

export default App
