// examples/vue/src/App.vue
<template>
  <UppyContextProvider :uppy="uppy">
    <main class="p-5 max-w-xl mx-auto">
      <h1 class="text-4xl font-bold my-4">Welcome to Vue.</h1>

      <UploadButton />

      <dialog
        ref="dialogRef"
        class="backdrop:bg-gray-500/50 rounded-lg shadow-xl p-0 fixed inset-0 m-auto"
      >
        <Webcam v-if="modalPlugin === 'webcam'" :close="closeModal" />
        <RemoteSource
          v-if="modalPlugin === 'dropbox'"
          id="Dropbox"
          :close="closeModal"
        />
        <ScreenCapture
          v-if="modalPlugin === 'screen-capture'"
          :close="closeModal"
        />
        <ImageEditor
          v-if="modalPlugin === 'image-editor' && selectedFile"
          :file="selectedFile"
          :close="closeModal"
        />
      </dialog>

      <article>
        <h2 class="text-2xl my-4">With list</h2>
        <Dropzone />
        <FilesList :edit-file="openImageEditorModal" />
      </article>

      <article>
        <h2 class="text-2xl my-4">With grid</h2>
        <Dropzone />
        <FilesGrid :columns="2" :edit-file="openImageEditorModal" />
      </article>

      <article>
        <h2 class="text-2xl my-4">With custom dropzone</h2>
        <CustomDropzone :openModal="openModal" />
      </article>
    </main>
  </UppyContextProvider>
</template>

<script setup lang="ts">
import Uppy, { type UppyFile } from '@uppy/core'
import UppyImageEditor from '@uppy/image-editor'
import UppyRemoteSources from '@uppy/remote-sources'
import UppyScreenCapture from '@uppy/screen-capture'
import Tus from '@uppy/tus'
import {
  Dropzone,
  FilesGrid,
  FilesList,
  UploadButton,
  UppyContextProvider,
} from '@uppy/vue'
import UppyWebcam from '@uppy/webcam'
import { computed, ref } from 'vue'
import CustomDropzone from './Dropzone.vue'
import ImageEditor from './ImageEditor.vue'
import RemoteSource from './RemoteSource.vue'
import ScreenCapture from './ScreenCapture.vue'
import Webcam from './Webcam.vue'

const dialogRef = ref<HTMLDialogElement | null>(null)
const modalPlugin = ref<
  'webcam' | 'dropbox' | 'screen-capture' | 'image-editor' | null
>(null)
const selectedFile = ref<UppyFile<any, any> | null>(null)

function openModal(plugin: 'webcam' | 'dropbox' | 'screen-capture') {
  modalPlugin.value = plugin
  dialogRef.value?.showModal()
}

function openImageEditorModal(file: UppyFile<any, any>) {
  selectedFile.value = file
  modalPlugin.value = 'image-editor'
  dialogRef.value?.showModal()
}

function closeModal() {
  modalPlugin.value = null
  selectedFile.value = null
  dialogRef.value?.close()
}

const uppy = computed(() =>
  new Uppy()
    .use(Tus, {
      endpoint: 'https://tusd.tusdemo.net/files/',
    })
    .use(UppyWebcam)
    .use(UppyScreenCapture)
    .use(UppyImageEditor)
    .use(UppyRemoteSources, { companionUrl: 'http://localhost:3020' }),
)
</script>

<style src="@uppy/vue/css/style.css"></style>
<style src="@uppy/vue/css/image-editor.css"></style>

// examples/react/src/App.tsx
import Uppy from '@uppy/core'
import {
  Dropzone,
  FilesGrid,
  FilesList,
  UploadButton,
  UppyContextProvider,
} from '@uppy/react'
import UppyRemoteSources from '@uppy/remote-sources'
import UppyScreenCapture from '@uppy/screen-capture'
import Tus from '@uppy/tus'
import UppyWebcam from '@uppy/webcam'
import React, { useRef, useState } from 'react'
import CustomDropzone from './CustomDropzone.tsx'
import { RemoteSource } from './RemoteSource.js'
import ScreenCapture from './ScreenCapture.tsx'
import Webcam from './Webcam.tsx'

import './app.css'
import '@uppy/react/dist/styles.css'

function App() {
  const [uppy] = useState(() =>
    new Uppy()
      .use(Tus, {
        endpoint: 'https://tusd.tusdemo.net/files/',
      })
      .use(UppyWebcam)
      .use(UppyScreenCapture)
      .use(UppyRemoteSources, { companionUrl: 'http://localhost:3020' }),
  )

  const dialogRef = useRef<HTMLDialogElement>(null)
  const [modalPlugin, setModalPlugin] = useState<
    'webcam' | 'dropbox' | 'screen-capture' | null
  >(null)

  function openModal(plugin: 'webcam' | 'dropbox' | 'screen-capture') {
    setModalPlugin(plugin)
    dialogRef.current?.showModal()
  }

  function closeModal() {
    setModalPlugin(null)
    dialogRef.current?.close()
  }

  return (
    <UppyContextProvider uppy={uppy}>
      <main className="p-5 max-w-xl mx-auto">
        <h1 className="text-4xl font-bold my-4">Welcome to React.</h1>

        <UploadButton />

        <dialog
          ref={dialogRef}
          className="backdrop:bg-gray-500/50 rounded-lg shadow-xl p-0 fixed inset-0 m-auto"
        >
          {(() => {
            switch (modalPlugin) {
              case 'webcam':
                return <Webcam close={() => closeModal()} />
              case 'dropbox':
                return <RemoteSource id="Dropbox" close={() => closeModal()} />
              case 'screen-capture':
                return <ScreenCapture close={() => closeModal()} />
              default:
                return null
            }
          })()}
        </dialog>

        <article>
          <h2 className="text-2xl my-4">With list</h2>
          <Dropzone />
          <FilesList />
        </article>

        <article>
          <h2 className="text-2xl my-4">With grid</h2>
          <Dropzone />
          <FilesGrid columns={2} />
        </article>

        <article>
          <h2 className="text-2xl my-4">With custom dropzone</h2>
          <CustomDropzone openModal={(plugin) => openModal(plugin)} />
        </article>
      </main>
    </UppyContextProvider>
  )
}

export default App
