// examples/vue/src/Webcam.vue
<template>
  <MediaCapture
    title="Camera"
    :close="props.close"
    :video-props="webcam.getVideoProps()"
    :primary-action-button-props="webcam.getSnapshotButtonProps()"
    primary-action-button-label="Snapshot"
    :record-button-props="webcam.getRecordButtonProps()"
    :stop-recording-button-props="webcam.getStopRecordingButtonProps()"
    :submit-button-props="webcam.getSubmitButtonProps()"
    :discard-button-props="webcam.getDiscardButtonProps()"
    :media-error="webcam.state.cameraError"
  />
</template>

<script setup lang="ts">
import { useWebcam } from '@uppy/vue'
import { onMounted } from 'vue'
import MediaCapture from './MediaCapture.vue'

const props = defineProps<{
  close: () => void
}>()

const webcam = useWebcam({ onSubmit: props.close })

onMounted(() => {
  webcam.value.start()
  return () => {
    webcam.value.stop()
  }
})
</script>

// examples/react/src/Webcam.tsx
import { useWebcam } from '@uppy/react'
import { useEffect } from 'react'
import MediaCapture from './MediaCapture.tsx'

export interface WebcamProps {
  close: () => void
}

export function Webcam({ close }: WebcamProps) {
  const {
    start,
    stop,
    getVideoProps,
    getSnapshotButtonProps,
    getRecordButtonProps,
    getStopRecordingButtonProps,
    getSubmitButtonProps,
    getDiscardButtonProps,
    state,
  } = useWebcam({ onSubmit: close })

  useEffect(() => {
    start()
    return () => {
      stop()
    }
  }, [start, stop])

  return (
    <MediaCapture
      title="Camera"
      close={close}
      getVideoProps={getVideoProps}
      mediaError={state.cameraError}
      getPrimaryActionButtonProps={getSnapshotButtonProps}
      primaryActionButtonLabel="Snapshot"
      getRecordButtonProps={getRecordButtonProps}
      getStopRecordingButtonProps={getStopRecordingButtonProps}
      getSubmitButtonProps={getSubmitButtonProps}
      getDiscardButtonProps={getDiscardButtonProps}
    />
  )
}

export default Webcam
