// packages/@uppy/svelte/src/lib/components/DashboardModal.svelte
<script
  lang="ts"
  generics="M extends import('@uppy/utils/lib/UppyFile').Meta, B extends import('@uppy/utils/lib/UppyFile').Body"
>
import type { Uppy } from "@uppy/core";
import DashboardPlugin, { type DashboardOptions } from "@uppy/dashboard";
import { onDestroy, onMount } from "svelte";

let container: HTMLElement;
let plugin: DashboardPlugin<M, B>;

export let uppy: Uppy<M, B>;
export let props: DashboardOptions<M, B> | undefined = {};
export let open: boolean;
let lastOpen: boolean = open;

export let plugins: string[] = [];

const installPlugin = () => {
	const options = {
		id: "svelte:DashboardModal",
		plugins,
		...props,
		target: container,
	} satisfies DashboardOptions<M, B>;

	uppy.use(DashboardPlugin<M, B>, options);
	plugin = uppy.getPlugin(options.id) as DashboardPlugin<M, B>;
	if (open) plugin.openModal();
};
const uninstallPlugin = (uppyInstance: Uppy<M, B> = uppy) => {
	if (plugin != null) uppyInstance.removePlugin(plugin);
};

onMount(() => installPlugin());

onDestroy(() => uninstallPlugin());
$: {
	const options = {
		id: "svelte:DashboardModal",
		plugins,
		...props,
		target: container,
	} satisfies DashboardOptions<M, B>;
	uppy.setOptions(options);
}
$: {
	if (open && !lastOpen) {
		plugin.openModal();
	}
	if (!open && lastOpen) {
		plugin.closeModal();
	}
	lastOpen = open;
}
</script>

<div class="uppy-Container" bind:this={container}></div>

// packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard-modal/dashboard-modal.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  Input,
  OnDestroy,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import Dashboard from '@uppy/dashboard';
import type { DashboardOptions } from '@uppy/dashboard';
import { Uppy } from '@uppy/core';
import { UppyAngularWrapper } from '../../utils/wrapper';
import { Body, Meta } from '@uppy/utils/lib/UppyFile';

@Component({
  selector: 'uppy-dashboard-modal',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DashboardModalComponent<M extends Meta, B extends Body>
  extends UppyAngularWrapper<M, B, DashboardOptions, Dashboard<M, B>>
  implements OnDestroy, OnChanges
{
  @Input() uppy: Uppy<M, B> = new Uppy();
  @Input() props: DashboardOptions = {};
  @Input() open: boolean = false;

  constructor(public el: ElementRef) {
    super();
  }

  ngOnInit() {
    this.onMount(
      {
        id: 'angular:DashboardModal',
        inline: false,
        target: this.el.nativeElement,
      },
      Dashboard,
    );
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.handleChanges(changes, Dashboard);
    // Handle dashboard-modal specific changes
    if (changes['open'] && this.open !== changes['open'].previousValue) {
      if (this.open && !changes['open'].previousValue) {
        this.plugin!.openModal();
      }
      if (!this.open && changes['open'].previousValue) {
        this.plugin!.closeModal();
      }
    }
  }

  ngOnDestroy(): void {
    this.uninstall();
  }
}
