// examples/vue/src/Dropzone.vue
<template>
  <input v-bind="getInputProps()" class="hidden" />
  <div
    v-bind="getRootProps()"
    role="button"
    class="border-2 border-dashed border-gray-300 rounded-lg p-6 bg-gray-50 transition-colors duration-200"
  >
    <div class="flex items-center justify-center gap-4">
      <input v-bind="getFileInputProps()" class="hidden" />
      <button type="button"
        v-bind="getButtonProps()"
        class="hover:bg-gray-100 transition-colors p-2 rounded-md flex flex-col items-center gap-2 text-sm"
      >
        <div class="bg-white shadow-md rounded-md p-1">
          <ProviderIcon provider="device" fill="#1269cf" />
        </div>
        Device
      </button>

      <button type="button"
        @click="() => props.openModal('webcam')"
        class="hover:bg-gray-100 transition-colors p-2 rounded-md flex flex-col items-center gap-2 text-sm"
      >
        <div class="bg-white shadow-md rounded-md p-1">
          <ProviderIcon provider="camera" fill="#02B383" />
        </div>
        Webcam
      </button>

      <button type="button"
        @click="() => props.openModal('screen-capture')"
        class="hover:bg-gray-100 transition-colors p-2 rounded-md flex flex-col items-center gap-2 text-sm"
      >
        <div class="bg-white shadow-md rounded-md p-1">
          <ProviderIcon provider="screen-capture" fill="#FF69B4" />
        </div>
        Screen Capture
      </button>

      <button type="button"
        @click="() => props.openModal('dropbox')"
        class="hover:bg-gray-100 transition-colors p-2 rounded-md flex flex-col items-center gap-2 text-sm"
      >
        <div class="bg-white shadow-md rounded-md p-1">
          <ProviderIcon provider="dropbox" />
        </div>
        Dropbox
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ProviderIcon, useDropzone, useFileInput } from '@uppy/vue'

const props = defineProps<{
  openModal: (plugin: 'webcam' | 'dropbox' | 'screen-capture') => void
}>()

const { getRootProps, getInputProps } = useDropzone({
  noClick: true,
})
const { getButtonProps, getInputProps: getFileInputProps } = useFileInput()
</script>

// packages/@uppy/components/src/Dropzone.tsx
/* eslint-disable jsx-a11y/click-events-have-key-events */
/* eslint-disable react/jsx-props-no-spreading */
import { h } from 'preact'
import { useMemo } from 'preact/hooks'
import { clsx } from 'clsx'
import type { UppyContext } from './types.js'
import { createDropzone } from './hooks/dropzone.js'

export type DropzoneProps = {
  width?: string
  height?: string
  note?: string
  noClick?: boolean
  ctx: UppyContext
}

export default function Dropzone(props: DropzoneProps) {
  const { width, height, note, noClick, ctx } = props

  const { getRootProps, getInputProps } = useMemo(
    () => createDropzone(ctx, { noClick }),
    [ctx, noClick],
  )

  return (
    <div className="uppy-reset" data-uppy-element="dropzone">
      <input {...getInputProps()} className="uppy:hidden" />
      <div
        {...getRootProps()}
        role="button"
        style={{
          width: width || '100%',
          height: height || '100%',
        }}
        className={clsx(
          'uppy:border-2 uppy:border-dashed uppy:border-gray-300',
          'uppy:rounded-lg uppy:p-6 uppy:bg-gray-50',
          'uppy:transition-colors uppy:duration-200',
          {
            'uppy:cursor-pointer uppy:hover:bg-blue-50': !noClick,
          },
        )}
      >
        <div className="uppy:flex uppy:flex-col uppy:items-center uppy:justify-center uppy:h-full uppy:space-y-3">
          <p className="uppy:text-gray-600">
            Drop files here or click to add them
          </p>
        </div>
        {note ?
          <div className="uppy:text-sm uppy:text-gray-500">{note}</div>
        : null}
      </div>
    </div>
  )
}
