// examples/vue3/src/Dropzone.vue
<template>
  <div>
    <input v-bind="getInputProps()" class="hidden" />
    <div
      v-bind="getRootProps()"
      class="border-2 border-dashed border-gray-300 rounded-lg p-6 bg-gray-50 transition-colors duration-200"
      :class="{ 'bg-blue-50': isDragging }"
    >
      <div class="flex flex-col items-center justify-center h-full space-y-3">
        <input v-bind="getFileInputProps()" class="hidden" />
        <button
          v-bind="getButtonProps()"
          class="hover:bg-gray-100 transition-colors p-2 rounded-md flex flex-col items-center gap-2 text-sm"
        >
          <div class="bg-white shadow-md rounded-md p-1">
            <ProviderIcon provider="device" fill="#02B383" />
          </div>
          Device
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useDropzone, useFileInput, ProviderIcon } from '@uppy/vue'
const { getRootProps, getInputProps, isDragging } = useDropzone({
  noClick: true,
})
const { getInputProps: getFileInputProps, getButtonProps } = useFileInput()
</script>

// packages/@uppy/components/src/Dropzone.tsx
/* eslint-disable jsx-a11y/click-events-have-key-events */
/* eslint-disable react/jsx-props-no-spreading */
import { h } from 'preact'
import { useMemo } from 'preact/hooks'
import { clsx } from 'clsx'
import type { UppyContext } from './types.js'
import { createDropzone } from './hooks/dropzone.js'

export type DropzoneProps = {
  width?: string
  height?: string
  note?: string
  noClick?: boolean
  ctx: UppyContext
}

export default function Dropzone(props: DropzoneProps) {
  const { width, height, note, noClick, ctx } = props

  const { isDragging, getRootProps, getInputProps } = useMemo(
    () => createDropzone(ctx, { noClick }),
    [ctx, noClick],
  )

  return (
    <div className="uppy-reset" data-uppy-element="dropzone">
      <input {...getInputProps()} className="uppy:hidden" />
      <div
        {...getRootProps()}
        role="button"
        style={{
          width: width || '100%',
          height: height || '100%',
        }}
        className={clsx(
          'uppy:border-2 uppy:border-dashed uppy:border-gray-300',
          'uppy:rounded-lg uppy:p-6 uppy:bg-gray-50',
          'uppy:transition-colors uppy:duration-200',
          {
            'uppy:bg-blue-50': isDragging,
          },
          {
            'uppy:cursor-pointer uppy:hover:bg-blue-50': !noClick,
          },
        )}
      >
        <div className="uppy:flex uppy:flex-col uppy:items-center uppy:justify-center uppy:h-full uppy:space-y-3">
          <p className="uppy:text-gray-600">
            Drop files here or click to add them
          </p>
        </div>
        {note ?
          <div className="uppy:text-sm uppy:text-gray-500">{note}</div>
        : null}
      </div>
    </div>
  )
}
