// packages/@uppy/svelte/src/lib/components/headless/Audio.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    Audio as PreactAudio,
    type AudioProps,
    type UppyContext,
  } from '@uppy/components'
  import { h as preactH } from 'preact'
  import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: Omit<AudioProps, 'ctx' | 'render'> = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactAudio, {
          ...props,
          ctx,
          render: (el, node) => {
            if (el) {
              mount(node, { target: el })
            }
          },
        } satisfies AudioProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>

// packages/@uppy/react/src/Audio.tsx
import { useEffect, useRef, useContext, createElement as h } from 'react'
import { Audio as PreactAudio, type AudioProps } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import { UppyContext as ReactUppyContext } from './UppyContextProvider.js'

export default function Audio(props: Omit<AudioProps, 'render' | 'ctx'>) {
  const ref = useRef(null)
  const ctx = useContext(ReactUppyContext)

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactAudio, {
          ...props,
          ctx,
        } satisfies AudioProps),
        ref.current,
      )
    }
  }, [ctx, props])

  return h('div', { ref })
}
