// packages/@uppy/svelte/src/components/DashboardModal.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { Uppy } from '@uppy/core';
  import DashboardPlugin from '@uppy/dashboard'

  let container: HTMLElement;
  let plugin: DashboardPlugin;

  export let uppy: Uppy;
  export let props: Object | undefined = {};
  export let open: boolean;
  let lastOpen: boolean = open;

  export let plugins: string[] = [];

  const installPlugin = () => {
    const options = {
      id: 'svelte:DashboardModal',
      plugins,
      ...props,
      target: container
    }

    uppy.use(DashboardPlugin, options);
    plugin = uppy.getPlugin(options.id) as DashboardPlugin;
    if(open) plugin.openModal();
  }
  const uninstallPlugin = (uppyInstance: Uppy = uppy) => {
    uppyInstance.removePlugin(plugin);
  }

  onMount(() => installPlugin())

  onDestroy(() => uninstallPlugin())
  $: {
    const options = {
      id: 'svelte:DashboardModal',
      plugins,
      ...props,
      target: container
    }
    uppy.setOptions(options)
  }
  $: {
    if(open && !lastOpen) {
      plugin.openModal()
    }
    if (!open && lastOpen) {
      plugin.closeModal()
    }
    lastOpen = open;
  }
</script>
<div bind:this={container} />

// packages/@uppy/react/src/DashboardModal.js
const React = require('react')
const PropTypes = require('prop-types')
const DashboardPlugin = require('@uppy/dashboard')
const basePropTypes = require('./propTypes').dashboard

const h = React.createElement

/**
 * React Component that renders a Dashboard for an Uppy instance in a Modal
 * dialog. Visibility of the Modal is toggled using the `open` prop.
 */

class DashboardModal extends React.Component {
  componentDidMount () {
    this.installPlugin()
  }

  componentDidUpdate (prevProps) {
    if (prevProps.uppy !== this.props.uppy) {
      this.uninstallPlugin(prevProps)
      this.installPlugin()
    }
    if (prevProps.open && !this.props.open) {
      this.plugin.closeModal()
    } else if (!prevProps.open && this.props.open) {
      this.plugin.openModal()
    }
  }

  componentWillUnmount () {
    this.uninstallPlugin()
  }

  installPlugin () {
    const uppy = this.props.uppy
    const options = {
      id: 'react:DashboardModal',
      ...this.props,
      onRequestCloseModal: this.props.onRequestClose,
    }

    if (!options.target) {
      options.target = this.container
    }

    delete options.uppy
    uppy.use(DashboardPlugin, options)

    this.plugin = uppy.getPlugin(options.id)
    if (this.props.open) {
      this.plugin.openModal()
    }
  }

  uninstallPlugin (props = this.props) {
    const uppy = props.uppy

    uppy.removePlugin(this.plugin)
  }

  render () {
    return h('div', {
      ref: (container) => {
        this.container = container
      },
    })
  }
}

DashboardModal.propTypes = { // Only check this prop type in the browser.
  target: typeof window !== 'undefined' ? PropTypes.instanceOf(window.HTMLElement) : PropTypes.any,
  open: PropTypes.bool,
  onRequestClose: PropTypes.func,
  closeModalOnClickOutside: PropTypes.bool,
  disablePageScrollWhenModalOpen: PropTypes.bool,
  ...basePropTypes,
}

DashboardModal.defaultProps = {
}

module.exports = DashboardModal
