// packages/@uppy/svelte/src/components/ProgressBar.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { Uppy } from '@uppy/core';
  import ProgressBarPlugin from '@uppy/progress-bar'

  let container: HTMLElement;
  let plugin: ProgressBarPlugin; 

  export let uppy: Uppy;
  export let props: Object | undefined = {};

  const installPlugin = () => {
    const options = {
      id: 'svelte:ProgressBar',
      inline: true,
      ...props,
      target: container
    }

    uppy.use(ProgressBarPlugin, options);
    plugin = uppy.getPlugin(options.id) as ProgressBarPlugin;
  }
  const uninstallPlugin = (uppyInstance: Uppy = uppy) => {
    if (plugin != null) uppyInstance.removePlugin(plugin);
  }

  onMount(() => installPlugin())

  onDestroy(() => uninstallPlugin())
  $: {
    const options = {
      id: 'svelte:ProgressBar',
      ...props,
      target: container
    }
    uppy.setOptions(options)
  }
</script>
<div class="uppy-Container" bind:this={container} />

// packages/@uppy/react/src/ProgressBar.js
const React = require('react')
const PropTypes = require('prop-types')
const ProgressBarPlugin = require('@uppy/progress-bar')
const uppyPropType = require('./propTypes').uppy

const h = React.createElement

/**
 * React component that renders a progress bar at the top of the page.
 */

class ProgressBar extends React.Component {
  componentDidMount () {
    this.installPlugin()
  }

  componentDidUpdate (prevProps) {
    if (prevProps.uppy !== this.props.uppy) {
      this.uninstallPlugin(prevProps)
      this.installPlugin()
    }
  }

  componentWillUnmount () {
    this.uninstallPlugin()
  }

  installPlugin () {
    const uppy = this.props.uppy
    const options = Object.assign(
      { id: 'react:ProgressBar' },
      this.props,
      { target: this.container }
    )
    delete options.uppy

    uppy.use(ProgressBarPlugin, options)

    this.plugin = uppy.getPlugin(options.id)
  }

  uninstallPlugin (props = this.props) {
    const uppy = props.uppy

    uppy.removePlugin(this.plugin)
  }

  render () {
    return h('div', {
      ref: (container) => {
        this.container = container
      }
    })
  }
}

ProgressBar.propTypes = {
  uppy: uppyPropType,
  fixed: PropTypes.bool,
  hideAfterFinish: PropTypes.bool
}
ProgressBar.defaultProps = {
}

module.exports = ProgressBar
