// packages/@uppy/svelte/src/lib/components/headless/ScreenCapture.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    ScreenCapture as PreactScreenCapture,
    type ScreenCaptureProps,
    type UppyContext,
  } from '@uppy/components'
  import { h as preactH } from 'preact'
  import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: Omit<ScreenCaptureProps, 'ctx' | 'render'> = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactScreenCapture, {
          ...props,
          ctx,
          render: (el, node) => {
            if (el) {
              mount(node, { target: el })
            }
          },
        } satisfies ScreenCaptureProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>

// packages/@uppy/react/src/ScreenCapture.tsx
import { useEffect, useRef, useContext, createElement as h } from 'react'
import type { ScreenCaptureOptions } from '@uppy/screen-capture'
import {
  ScreenCapture as PreactScreenCapture,
  type ScreenCaptureProps,
} from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import { UppyContext } from './UppyContextProvider.js'

export default function ScreenCapture(
  props: Omit<ScreenCaptureOptions, 'target'>,
) {
  const ref = useRef(null)
  const ctx = useContext(UppyContext)

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactScreenCapture, {
          ...props,
          ctx,
        } satisfies ScreenCaptureProps),
        ref.current,
      )
    }
  }, [ctx, props])

  return <div ref={ref} />
}
