// packages/@uppy/svelte/src/lib/components/headless/Dropzone.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    Dropzone as PreactDropzone,
    type DropzoneProps,
    type UppyContext,
  } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: Omit<DropzoneProps, 'ctx'> = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactDropzone, {
          ...props,
          ctx,
        } satisfies DropzoneProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>

// packages/@uppy/react/src/headless/Dropzone.tsx
import { useEffect, useRef, useContext, createElement as h } from 'react'
import {
  Dropzone as PreactDropzone,
  type DropzoneProps,
} from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import { UppyContext } from './UppyContextProvider.js'

export default function Dropzone(props: Omit<DropzoneProps, 'ctx'>) {
  const ref = useRef(null)
  const ctx = useContext(UppyContext)

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactDropzone, {
          ...props,
          ctx,
        } satisfies DropzoneProps),
        ref.current,
      )
    }
  }, [ctx, props])

  return <div ref={ref} />
}
