// packages/@uppy/svelte/src/lib/components/headless/Webcam.svelte
<script lang="ts">
  import { getContext, mount } from 'svelte'
  import {
    Webcam as PreactWebcam,
    type WebcamProps,
    type UppyContext,
  } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
  import { UppyContextKey } from './UppyContextProvider.svelte'

  const props: Omit<WebcamProps, 'ctx'> = $props()
  const ctx = getContext<UppyContext>(UppyContextKey)
  let container: HTMLElement

  $effect(() => {
    if (container) {
      preactRender(
        preactH(PreactWebcam, {
          ...props,
          ctx,
        } satisfies WebcamProps),
        container,
      )
    }
  })
</script>

<div bind:this={container}></div>

// packages/@uppy/react/src/headless/Webcam.tsx
import { useEffect, useRef, useContext, createElement as h } from 'react'
import { Webcam as PreactWebcam, type WebcamProps } from '@uppy/components'
import { h as preactH } from 'preact'
import { render as preactRender } from 'preact/compat'
import { UppyContext } from './UppyContextProvider.js'

export default function Webcam(props: Omit<WebcamProps, 'ctx'>) {
  const ref = useRef(null)
  const ctx = useContext(UppyContext)

  useEffect(() => {
    if (ref.current) {
      preactRender(
        preactH(PreactWebcam, {
          ...props,
          ctx,
        } satisfies WebcamProps),
        ref.current,
      )
    }
  }, [ctx, props])

  return <div ref={ref} />
}
