// packages/@uppy/vue/src/DashboardModal.vue
<template>
  <div ref="container" />
</template>
<script lang="ts">
import Vue, { PropType } from 'vue'
import type { Uppy, Plugin } from '@uppy/core'
import DashboardPlugin from '@uppy/dashboard'
import { shallowEqualObjects } from 'shallow-equal'

interface Data {
  plugin: DashboardPlugin 
}
interface Props {
  uppy: Uppy,
  props: Object,
  plugins: Plugin[],
  open: boolean 
}
interface Methods {
  installPlugin(): void,
  uninstallPlugin(uppy: Uppy): void,
}

export default Vue.extend<Data, Methods, unknown, Props>({
  data () {
    return {
      plugin: {} as Plugin
    }
  },
  props: {
    uppy: {
      required: true
    },
    props: {
      type: Object
    },
    plugins: {
      type: Array
    },
    open: {
      type: Boolean,
      required: true
    }
  },
  mounted () {
    this.installPlugin()
  },
  methods: {
    installPlugin () {
      const uppy = this.uppy
      const options = {
        id: 'vue:DashboardModal',
        plugins: this.plugins,
        ...this.props,
        target: this.$refs.container
      }
      uppy.use(DashboardPlugin, options)
      this.plugin = uppy.getPlugin(options.id) as DashboardPlugin
      if (this.open) {
        this.plugin.openModal()
      }
    },
    uninstallPlugin (uppy: Uppy) {
      uppy.removePlugin(this.plugin)
    }
  },
  beforeDestroy () {
    this.uninstallPlugin(this.uppy)
  },
  watch: {
    uppy (current: Uppy, old: Uppy) {
      if (old !== current) {
        this.uninstallPlugin(old)
        this.installPlugin()
      }
    },
    open (current, old) {
      if (current && !old) {
        this.plugin.openModal()
      }
      if (!current && old) {
        this.plugin.closeModal()
      }
    },
    props (current, old) {
      if (!shallowEqualObjects(current, old)) {
        this.plugin.setOptions(current)
      }
    }
  }
})
</script>

// packages/@uppy/svelte/src/components/DashboardModal.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { Uppy } from '@uppy/core';
  import DashboardPlugin from '@uppy/dashboard'

  let container: HTMLElement;
  let plugin: DashboardPlugin;

  export let uppy: Uppy;
  export let props: Object | undefined = {};
  export let open: boolean;
  let lastOpen: boolean = open;

  export let plugins: string[] = [];

  const installPlugin = () => {
    const options = {
      id: 'svelte:DashboardModal',
      plugins,
      ...props,
      target: container
    }

    uppy.use(DashboardPlugin, options);
    plugin = uppy.getPlugin(options.id) as DashboardPlugin;
    if(open) plugin.openModal();
  }
  const uninstallPlugin = (uppyInstance: Uppy = uppy) => {
    uppyInstance.removePlugin(plugin);
  }

  onMount(() => installPlugin())

  onDestroy(() => uninstallPlugin())
  $: {
    const options = {
      id: 'svelte:DashboardModal',
      plugins,
      ...props,
      target: container
    }
    uppy.setOptions(options)
  }
  $: {
    if(open && !lastOpen) {
      plugin.openModal()
    }
    if (!open && lastOpen) {
      plugin.closeModal()
    }
    lastOpen = open;
  }
</script>
<div bind:this={container} />
