// packages/@uppy/react/src/DragDrop.js
const React = require('react')
const DragDropPlugin = require('@uppy/drag-drop')
const propTypes = require('./propTypes')

const h = React.createElement

/**
 * React component that renders an area in which files can be dropped to be
 * uploaded.
 */

class DragDrop extends React.Component {
  componentDidMount () {
    this.installPlugin()
  }

  componentDidUpdate (prevProps) {
    if (prevProps.uppy !== this.props.uppy) {
      this.uninstallPlugin(prevProps)
      this.installPlugin()
    }
  }

  componentWillUnmount () {
    this.uninstallPlugin()
  }

  installPlugin () {
    const uppy = this.props.uppy
    const options = {
      id    : 'react:DragDrop',
      ...this.props,
      target: this.container,
    }
    delete options.uppy

    uppy.use(DragDropPlugin, options)

    this.plugin = uppy.getPlugin(options.id)
  }

  uninstallPlugin (props = this.props) {
    const uppy = props.uppy

    uppy.removePlugin(this.plugin)
  }

  render () {
    return h('div', {
      ref: (container) => {
        this.container = container
      },
    })
  }
}

DragDrop.propTypes = {
  uppy  : propTypes.uppy,
  locale: propTypes.locale,
}
DragDrop.defaultProps = {
}

module.exports = DragDrop

// packages/@uppy/svelte/src/components/DragDrop.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { Uppy, Plugin } from '@uppy/core';
  import DragDropPlugin from '@uppy/drag-drop'

  let container: HTMLElement;
  let plugin: DragDropPlugin; 

  export let uppy: Uppy;
  export let props: Object | undefined = {};

  const installPlugin = () => {
    const options = {
      id: 'svelte:DragDrop',
      inline: true,
      ...props,
      target: container
    }

    uppy.use(DragDropPlugin, options);
    plugin = uppy.getPlugin(options.id) as DragDropPlugin;
  }
  const uninstallPlugin = (uppyInstance: Uppy = uppy) => {
    uppyInstance.removePlugin(plugin);
  }

  onMount(() => installPlugin())

  onDestroy(() => uninstallPlugin())
  $: {
    const options = {
      id: 'svelte:DragDrop',
      ...props,
      target: container
    }
    uppy.setOptions(options)
  }
</script>
<div bind:this={container} />
